name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: trgchinhh
          token: ${{ secrets.GITHUB_TOKEN }}

          template: classic
          base: header, repositories

          plugin_languages: yes
